"""esquema inicial — fotografia fiel do banco em 03/09/2026

Revisão inicial da Fase 0. **Não redesenha nada**: reproduz o esquema que o banco de
produção tem hoje, tabela por tabela e coluna por coluna, para que toda alteração a
partir daqui seja mensurável e reversível.

Duas divergências entre os modelos e o banco vivo foram encontradas ao gerar esta
revisão, e ambas estão registradas como B-13 no AUDIT_ANARA_MASTER.md:

1. Cinco índices que os modelos declaram não existem em produção — as colunas foram
   acrescentadas por ALTER TABLE, e `app/migrations.py` não cria índice nesse caminho.
   Aqui eles ficam **comentados**, com o motivo ao lado: a revisão fotografa o que
   existe. Criá-los é uma decisão de etapa própria, não um efeito colateral da Fase 0.

2. Quatro colunas booleanas — `cliente.ativo`, `cotacao.freight_incluso`,
   `produto.precisa_revisao` e `toalhapreco.preco_final` — estão declaradas INTEGER no
   banco e BOOLEAN no modelo (mesma origem: ALTER TABLE). Ficam BOOLEAN aqui, que é o
   tipo do modelo: no SQLite as duas guardam 0/1 e se comportam igual, e no PostgreSQL
   da Onda 4 BOOLEAN é o tipo certo. A diferença fica anotada, não corrigida agora.

Revision ID: 0001
Revises:
Create Date: 2026-09-03 08:12:13.650085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel                     # tipos do SQLModel (AutoString)


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baseimportacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('importado_em', sa.DateTime(), nullable=False),
    sa.Column('nome_arquivo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('observacoes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('icms_pct', sa.Float(), nullable=False),
    sa.Column('pis_cofins_pct', sa.Float(), nullable=False),
    sa.Column('encargo_financeiro_pct', sa.Float(), nullable=False),
    sa.Column('comissao_tabela_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('origem_uf', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icms_por_estado_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),  # produção: nullable (B-13)
    sa.Column('cenarios_fiscais_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),  # produção: nullable (B-13)
    sa.Column('cambio_usd_brl', sa.Float(), nullable=True),
    sa.Column('frete_usd_kg', sa.Float(), nullable=True),
    sa.Column('outras_desp_usd_un', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cnpj_cpf', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cidade_uf', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contato_nome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('departamento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),  # produção: nullable (B-13)
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cmtpreco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('familia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('construcao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cmt_usd', sa.Float(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('fonte', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('condicaopagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encargo_pct', sa.Float(), nullable=True),
    sa.Column('encargo_confirmado', sa.Boolean(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('condicaopagamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_condicaopagamento_codigo'), ['codigo'], unique=True)

    op.create_table('estadofiscal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uf', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aliquota_interestadual', sa.Float(), nullable=False),
    sa.Column('aliquota_interna', sa.Float(), nullable=False),
    sa.Column('base_simples', sa.Float(), nullable=True),
    sa.Column('base_dupla', sa.Float(), nullable=True),
    sa.Column('fem', sa.Float(), nullable=True),
    sa.Column('carga_final', sa.Float(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('fonte', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('estadofiscal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estadofiscal_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_estadofiscal_uf'), ['uf'], unique=False)

    op.create_table('fornecedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sa.Enum('importado_ktc', 'nacional', 'outro', name='tipofornecedor'), nullable=False),
    sa.Column('pais', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('moeda_custo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost_method_padrao', sa.Enum('ktc_calculated', 'ktc_quoted', 'national_supplier', 'manual', 'legacy_excel', name='costmethod'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('observacoes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fornecedor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fornecedor_codigo'), ['codigo'], unique=True)

    op.create_table('materialpreco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thread_count', sa.Integer(), nullable=True),
    sa.Column('weave', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cotton_pct', sa.Float(), nullable=True),
    sa.Column('poliester_pct', sa.Float(), nullable=True),
    sa.Column('plain_or_stripe', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price_usd_m2', sa.Float(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('fonte', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fonte_data', sa.Date(), nullable=True),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ncmregra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('familia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao_ncm', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ncm', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ii_original', sa.Float(), nullable=True),
    sa.Column('reducao_preferencial', sa.Float(), nullable=True),
    sa.Column('ii_preferencial', sa.Float(), nullable=True),
    sa.Column('prioridade', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('confiavel', sa.Boolean(), nullable=False),
    sa.Column('fonte', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parametroktc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('escopo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('fonte', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parametroktc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parametroktc_chave'), ['chave'], unique=False)
        batch_op.create_index(batch_op.f('ix_parametroktc_escopo'), ['escopo'], unique=False)

    op.create_table('premissa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor_num', sa.Float(), nullable=True),
    sa.Column('valor_txt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unidade', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('fonte', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fonte_data', sa.Date(), nullable=True),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('premissa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_premissa_chave'), ['chave'], unique=False)

    op.create_table('regrafiscalvenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origem', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('destino', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contribuinte', sa.Boolean(), nullable=False),
    sa.Column('icms_venda', sa.Float(), nullable=False),
    sa.Column('regra', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prioridade', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('fonte', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regrafiscalvenda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regrafiscalvenda_contribuinte'), ['contribuinte'], unique=False)
        batch_op.create_index(batch_op.f('ix_regrafiscalvenda_destino'), ['destino'], unique=False)
        batch_op.create_index(batch_op.f('ix_regrafiscalvenda_origem'), ['origem'], unique=False)

    op.create_table('toalhapreco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('familia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subcategoria', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('composicao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('yarn_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gsm', sa.Integer(), nullable=True),
    sa.Column('plain_or_stripe', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('acabamento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price_usd_kg', sa.Float(), nullable=False),
    sa.Column('preco_final', sa.Boolean(), nullable=True),  # produção: nullable (B-13)
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('fonte', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cotacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('vendedor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('rascunho', 'enviada', 'fechada', 'perdida', 'pedido', name='statuscotacao'), nullable=False),
    sa.Column('condicao_pagamento', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estado_destino', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado_origem', sqlmodel.sql.sqltypes.AutoString(), nullable=True),  # produção: nullable (B-13)
    sa.Column('contribuinte_icms', sa.Boolean(), nullable=True),  # produção: nullable (B-13)
    sa.Column('frete', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('observacoes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('validade_em', sa.DateTime(), nullable=True),
    sa.Column('base_importacao_id', sa.Integer(), nullable=True),
    sa.Column('pdf_gerado_em', sa.DateTime(), nullable=True),
    sa.Column('arquivada_em', sa.DateTime(), nullable=True),
    sa.Column('arquivada_motivo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('validade_dias', sa.Integer(), nullable=True),  # produção: nullable (B-13)
    sa.Column('prazo_entrega', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contato_nome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('departamento_contato', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('freight_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),  # produção: nullable (B-13)
    sa.Column('freight_valor', sa.Float(), nullable=True),
    sa.Column('freight_incluso', sa.Boolean(), nullable=True),  # produção: nullable (B-13)
    sa.Column('freight_notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('termos_texto', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emitida_em', sa.DateTime(), nullable=True),
    sa.Column('aceite_responsavel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('aceite_cargo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('aceite_departamento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('aceite_em', sa.DateTime(), nullable=True),
    sa.Column('local_entrega', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('endereco_entrega', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('observacoes_pedido', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('icms_aplicado', sa.Float(), nullable=True),
    sa.Column('icms_regra', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pis_cofins_pct', sa.Float(), nullable=True),
    sa.Column('encargo_financeiro_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['base_importacao_id'], ['baseimportacao.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # (nenhum índice a criar em 'cotacao' — ver abaixo)
    # AUSENTE NO BANCO DE PRODUÇÃO — ver B-13 no AUDIT_ANARA_MASTER.md.
    # O modelo declara este índice, mas a coluna foi acrescentada depois por
    # ALTER TABLE (app/migrations.py), que não cria índice. A revisão inicial
    # fotografa o banco como ele É; criar o índice é decisão de outra etapa.
    # batch_op.create_index(batch_op.f('ix_cotacao_numero'), ['numero'], unique=False)

    op.create_table('margemregra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('familia', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sku_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('min_thread_count', sa.Integer(), nullable=True),
    sa.Column('max_thread_count', sa.Integer(), nullable=True),
    sa.Column('margem_pct', sa.Float(), nullable=False),
    sa.Column('prioridade', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome_original', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('especificacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('custo_unitario', sa.Float(), nullable=True),
    sa.Column('preco_base', sa.Float(), nullable=True),
    sa.Column('base_importacao_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('cost_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('custo_confianca', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('precisa_revisao', sa.Boolean(), nullable=True),  # produção: nullable (B-13)
    sa.Column('revisao_motivo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('custo_ref_valor', sa.Float(), nullable=True),
    sa.Column('custo_ref_moeda', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('custo_ref_data', sa.Date(), nullable=True),
    sa.Column('custo_ref_documento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('custo_ref_cliente', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('custo_ref_tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('custo_ref_nota', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('exw_calculado_usd', sa.Float(), nullable=True),
    sa.Column('exw_calculado_em', sa.DateTime(), nullable=True),
    sa.Column('exw_cotado_usd', sa.Float(), nullable=True),
    sa.Column('exw_cotado_data', sa.Date(), nullable=True),
    sa.Column('exw_cotado_fonte', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('exw_cotado_cliente', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('exw_diferenca_usd', sa.Float(), nullable=True),
    sa.Column('exw_diferenca_pct', sa.Float(), nullable=True),
    sa.Column('ncm', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ii_aplicado', sa.Float(), nullable=True),
    sa.Column('peso_kg', sa.Float(), nullable=True),
    sa.Column('peso_fonte', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('peso_tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('peso_data', sa.Date(), nullable=True),
    sa.Column('peso_documento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preco_ktc_usd', sa.Float(), nullable=True),
    sa.Column('frete_usd_un', sa.Float(), nullable=True),
    sa.Column('custo_net_usd', sa.Float(), nullable=True),
    sa.Column('cotacao_origem', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('familia', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subcategoria', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thread_count', sa.Integer(), nullable=True),
    sa.Column('weave', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cotton_pct', sa.Float(), nullable=True),
    sa.Column('poliester_pct', sa.Float(), nullable=True),
    sa.Column('largura_cm', sa.Float(), nullable=True),
    sa.Column('comprimento_cm', sa.Float(), nullable=True),
    sa.Column('gsm', sa.Integer(), nullable=True),
    sa.Column('plain_or_stripe', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('yarn_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('construcao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fechamento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('acabamento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('material_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('margem_padrao_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['base_importacao_id'], ['baseimportacao.id'], ),
    # FK AUSENTE NO BANCO DE PRODUÇÃO (B-13): a coluna fornecedor_id foi
    # acrescentada por ALTER TABLE, que no SQLite não cria chave estrangeira.
    # sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produto', schema=None) as batch_op:
        # AUSENTE NO BANCO DE PRODUÇÃO — ver B-13 no AUDIT_ANARA_MASTER.md.
        # O modelo declara este índice, mas a coluna foi acrescentada depois por
        # ALTER TABLE (app/migrations.py), que não cria índice. A revisão inicial
        # fotografa o banco como ele É; criar o índice é decisão de outra etapa.
        # batch_op.create_index(batch_op.f('ix_produto_cost_method'), ['cost_method'], unique=False)
        # AUSENTE NO BANCO DE PRODUÇÃO — ver B-13 no AUDIT_ANARA_MASTER.md.
        # O modelo declara este índice, mas a coluna foi acrescentada depois por
        # ALTER TABLE (app/migrations.py), que não cria índice. A revisão inicial
        # fotografa o banco como ele É; criar o índice é decisão de outra etapa.
        # batch_op.create_index(batch_op.f('ix_produto_custo_confianca'), ['custo_confianca'], unique=False)
        # AUSENTE NO BANCO DE PRODUÇÃO — ver B-13 no AUDIT_ANARA_MASTER.md.
        # O modelo declara este índice, mas a coluna foi acrescentada depois por
        # ALTER TABLE (app/migrations.py), que não cria índice. A revisão inicial
        # fotografa o banco como ele É; criar o índice é decisão de outra etapa.
        # batch_op.create_index(batch_op.f('ix_produto_familia'), ['familia'], unique=False)
        # AUSENTE NO BANCO DE PRODUÇÃO — ver B-13 no AUDIT_ANARA_MASTER.md.
        # O modelo declara este índice, mas a coluna foi acrescentada depois por
        # ALTER TABLE (app/migrations.py), que não cria índice. A revisão inicial
        # fotografa o banco como ele É; criar o índice é decisão de outra etapa.
        # batch_op.create_index(batch_op.f('ix_produto_fornecedor_id'), ['fornecedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_produto_sku_key'), ['sku_key'], unique=True)

    op.create_table('cotacaoitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cotacao_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('nome_produto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('especificacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('custo_unitario', sa.Float(), nullable=False),
    sa.Column('preco_base', sa.Float(), nullable=False),
    sa.Column('preco_negociado', sa.Float(), nullable=False),
    sa.Column('margem_liquida', sa.Float(), nullable=False),
    sa.Column('faturamento', sa.Float(), nullable=False),
    sa.Column('custo_total', sa.Float(), nullable=False),
    sa.Column('lucro', sa.Float(), nullable=False),
    sa.Column('diferenca_pct_vs_base', sa.Float(), nullable=True),
    sa.Column('modo_edicao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor_editado', sa.Float(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('fornecedor_nome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cost_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('margem_padrao_pct', sa.Float(), nullable=True),
    sa.Column('margem_regra', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comissao_pct', sa.Float(), nullable=True),
    sa.Column('impostos', sa.Float(), nullable=True),
    sa.Column('comissao_valor', sa.Float(), nullable=True),
    sa.Column('markup_implicito', sa.Float(), nullable=True),
    sa.Column('memoria_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['cotacao_id'], ['cotacao.id'], ),
    # FK AUSENTE NO BANCO DE PRODUÇÃO (B-13): a coluna fornecedor_id foi
    # acrescentada por ALTER TABLE, que no SQLite não cria chave estrangeira.
    # sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custoreferencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('sku_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('moeda', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_ref', sa.Date(), nullable=True),
    sa.Column('documento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cliente_documento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confianca', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('aplicado', sa.Boolean(), nullable=False),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custoreferencia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custoreferencia_produto_id'), ['produto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custoreferencia_sku_key'), ['sku_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custoreferencia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custoreferencia_sku_key'))
        batch_op.drop_index(batch_op.f('ix_custoreferencia_produto_id'))

    op.drop_table('custoreferencia')
    op.drop_table('cotacaoitem')
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produto_sku_key'))
        # AUSENTE NO BANCO DE PRODUÇÃO — ver B-13 no AUDIT_ANARA_MASTER.md.
        # O modelo declara este índice, mas a coluna foi acrescentada depois por
        # ALTER TABLE (app/migrations.py), que não cria índice. A revisão inicial
        # fotografa o banco como ele É; criar o índice é decisão de outra etapa.
        # batch_op.drop_index(batch_op.f('ix_produto_fornecedor_id'))
        # AUSENTE NO BANCO DE PRODUÇÃO — ver B-13 no AUDIT_ANARA_MASTER.md.
        # O modelo declara este índice, mas a coluna foi acrescentada depois por
        # ALTER TABLE (app/migrations.py), que não cria índice. A revisão inicial
        # fotografa o banco como ele É; criar o índice é decisão de outra etapa.
        # batch_op.drop_index(batch_op.f('ix_produto_familia'))
        # AUSENTE NO BANCO DE PRODUÇÃO — ver B-13 no AUDIT_ANARA_MASTER.md.
        # O modelo declara este índice, mas a coluna foi acrescentada depois por
        # ALTER TABLE (app/migrations.py), que não cria índice. A revisão inicial
        # fotografa o banco como ele É; criar o índice é decisão de outra etapa.
        # batch_op.drop_index(batch_op.f('ix_produto_custo_confianca'))
        # AUSENTE NO BANCO DE PRODUÇÃO — ver B-13 no AUDIT_ANARA_MASTER.md.
        # O modelo declara este índice, mas a coluna foi acrescentada depois por
        # ALTER TABLE (app/migrations.py), que não cria índice. A revisão inicial
        # fotografa o banco como ele É; criar o índice é decisão de outra etapa.
        # batch_op.drop_index(batch_op.f('ix_produto_cost_method'))

    op.drop_table('produto')
    op.drop_table('margemregra')
    # (nenhum índice a criar em 'cotacao' — ver abaixo)
    # AUSENTE NO BANCO DE PRODUÇÃO — ver B-13 no AUDIT_ANARA_MASTER.md.
    # O modelo declara este índice, mas a coluna foi acrescentada depois por
    # ALTER TABLE (app/migrations.py), que não cria índice. A revisão inicial
    # fotografa o banco como ele É; criar o índice é decisão de outra etapa.
    # batch_op.drop_index(batch_op.f('ix_cotacao_numero'))

    op.drop_table('cotacao')
    op.drop_table('toalhapreco')
    with op.batch_alter_table('regrafiscalvenda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regrafiscalvenda_origem'))
        batch_op.drop_index(batch_op.f('ix_regrafiscalvenda_destino'))
        batch_op.drop_index(batch_op.f('ix_regrafiscalvenda_contribuinte'))

    op.drop_table('regrafiscalvenda')
    with op.batch_alter_table('premissa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_premissa_chave'))

    op.drop_table('premissa')
    with op.batch_alter_table('parametroktc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parametroktc_escopo'))
        batch_op.drop_index(batch_op.f('ix_parametroktc_chave'))

    op.drop_table('parametroktc')
    op.drop_table('ncmregra')
    op.drop_table('materialpreco')
    with op.batch_alter_table('fornecedor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fornecedor_codigo'))

    op.drop_table('fornecedor')
    with op.batch_alter_table('estadofiscal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estadofiscal_uf'))
        batch_op.drop_index(batch_op.f('ix_estadofiscal_estado'))

    op.drop_table('estadofiscal')
    with op.batch_alter_table('condicaopagamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_condicaopagamento_codigo'))

    op.drop_table('condicaopagamento')
    op.drop_table('cmtpreco')
    op.drop_table('cliente')
    op.drop_table('baseimportacao')
    # ### end Alembic commands ###
